### ISSUE TITLE
can not add 'click' event

### ISSUE THREAD

**Issue by chenshaomou** [roeierez/infinite-list#13]
can not add 'click' event

**Comment by krishnaff** [comment]
Yes, any pointers on how to add a click event on mobile please? (clicks register fine on the browser). 
I tried touchstart, touchend etc, but a click/tap is not registering on any of the wrapped divs. :(
Thanks

**Comment by roeierez** [comment]
I just committed a fix on master
Can you tell me if you events are fired?
By the way as there is now a big deployment that uses this list I am improving it intensively in the next days. The improvements are done at the branch native_scroller (which implies on adding native scroller support for desktop). More issues will be solved there and when I feel it is robust enough I will merge to master.

**Comment by roeierez** [comment]
The scroll implementation has swallowed the touch start event.
Fixed it.

**Comment by krishnaff** [comment]
hello @roeierez this works really well now. the best plugin without any external dependencies. thanks! :)
