### ISSUE TITLE
Add/remove items from dataset

### ISSUE THREAD

**Issue by rodolfoag** [roeierez/infinite-list#7]
Is there a way to add items do the list after pageFetcher->pageCallback had been called with hasMore = false?
If the list is fully rendered and an item from the dataset is removed, how do I removed it from the list?

Thx!

**Comment by roeierez** [comment]
You just need to call refresh(). This will trigger re-render the new data.
Before invoking refresh, make sure the itemRenderer is updated to render the new items.

**Comment by roeierez** [comment]
Was that helpful and working for you?
